CREATE TABLE ACT_GE_PROPERTY (
    NAME_ VARCHAR(64),
    VALUE_ VARCHAR(300),
    REV_ INTEGER,
    PRIMARY KEY (NAME_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

INSERT INTO ACT_GE_PROPERTY
VALUES ('schema.version', '5.10', 1);

INSERT INTO ACT_GE_PROPERTY
VALUES ('schema.history', 'create(5.10)', 1);

INSERT INTO ACT_GE_PROPERTY
VALUES ('next.dbid', '1', 1);

CREATE TABLE ACT_GE_BYTEARRAY (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    NAME_ VARCHAR(255),
    DEPLOYMENT_ID_ VARCHAR(64),
    BYTES_ LONGBLOB,
    GENERATED_ TINYINT,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE ACT_RE_DEPLOYMENT (
    ID_ VARCHAR(64),
    NAME_ VARCHAR(255),
    DEPLOY_TIME_ TIMESTAMP,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE ACT_RU_EXECUTION (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    PROC_INST_ID_ VARCHAR(64),
    BUSINESS_KEY_ VARCHAR(255),
    PARENT_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    SUPER_EXEC_ VARCHAR(64),
    ACT_ID_ VARCHAR(255),
    IS_ACTIVE_ TINYINT,
    IS_CONCURRENT_ TINYINT,
    IS_SCOPE_ TINYINT,
    IS_EVENT_SCOPE_ TINYINT,
    SUSPENSION_STATE_ INTEGER,
    CACHED_ENT_STATE_ INTEGER,
    PRIMARY KEY (ID_),
    UNIQUE ACT_UNIQ_RU_BUS_KEY (PROC_DEF_ID_, BUSINESS_KEY_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE ACT_RU_JOB (
    ID_ VARCHAR(64) NOT NULL,
	  REV_ INTEGER,
    TYPE_ VARCHAR(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP,
    LOCK_OWNER_ VARCHAR(255),
    EXCLUSIVE_ boolean,
    EXECUTION_ID_ VARCHAR(64),
    PROCESS_INSTANCE_ID_ VARCHAR(64),
    RETRIES_ INTEGER,
    EXCEPTION_STACK_ID_ VARCHAR(64),
    EXCEPTION_MSG_ VARCHAR(4000),
    DUEDATE_ TIMESTAMP NULL,
    REPEAT_ VARCHAR(255),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE ACT_RE_PROCDEF (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    CATEGORY_ VARCHAR(255),
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255),
    VERSION_ INTEGER,
    DEPLOYMENT_ID_ VARCHAR(64),
    RESOURCE_NAME_ VARCHAR(4000),
    DGRM_RESOURCE_NAME_ VARCHAR(4000),
    HAS_START_FORM_KEY_ TINYINT,
    SUSPENSION_STATE_ INTEGER,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE ACT_RU_TASK (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    NAME_ VARCHAR(255),
    PARENT_TASK_ID_ VARCHAR(64),
    DESCRIPTION_ VARCHAR(4000),
    TASK_DEF_KEY_ VARCHAR(255),
    OWNER_ VARCHAR(64),
    ASSIGNEE_ VARCHAR(64),
    DELEGATION_ VARCHAR(64),
    PRIORITY_ INTEGER,
    CREATE_TIME_ TIMESTAMP,
    DUE_DATE_ datetime,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE ACT_RU_IDENTITYLINK (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    GROUP_ID_ VARCHAR(64),
    TYPE_ VARCHAR(255),
    USER_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE ACT_RU_VARIABLE (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    TYPE_ VARCHAR(255) NOT NULL,
    NAME_ VARCHAR(255) NOT NULL,
    EXECUTION_ID_ VARCHAR(64),
	  PROC_INST_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    BYTEARRAY_ID_ VARCHAR(64),
    DOUBLE_ DOUBLE,
    LONG_ bigint,
    TEXT_ VARCHAR(4000),
    TEXT2_ VARCHAR(4000),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE TABLE ACT_RU_EVENT_SUBSCR (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    EVENT_TYPE_ VARCHAR(255) NOT NULL,
    EVENT_NAME_ VARCHAR(255),
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    ACTIVITY_ID_ VARCHAR(64),
    CONFIGURATION_ VARCHAR(255),
    CREATED_ TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

CREATE index ACT_IDX_EXEC_BUSKEY ON ACT_RU_EXECUTION(BUSINESS_KEY_);
CREATE index ACT_IDX_TASK_CREATE ON ACT_RU_TASK(CREATE_TIME_);
CREATE index ACT_IDX_IDENT_LNK_USER ON ACT_RU_IDENTITYLINK(USER_ID_);
CREATE index ACT_IDX_IDENT_LNK_GROUP ON ACT_RU_IDENTITYLINK(GROUP_ID_);
CREATE index ACT_IDX_EVENT_SUBSCR_CONFIG_ ON ACT_RU_EVENT_SUBSCR(CONFIGURATION_);
CREATE index ACT_IDX_VARIABLE_TASK_ID ON ACT_RU_VARIABLE(TASK_ID_);
CREATE index ACT_IDX_ATHRZ_PROCEDEF ON ACT_RU_IDENTITYLINK(PROC_DEF_ID_);

ALTER TABLE ACT_GE_BYTEARRAY
    ADD CONSTRAINT ACT_FK_BYTEARR_DEPL
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_RE_DEPLOYMENT (ID_);

ALTER TABLE ACT_RE_PROCDEF
    ADD CONSTRAINT ACT_UNIQ_PROCDEF
    UNIQUE (KEY_,VERSION_);
    
ALTER TABLE ACT_RU_EXECUTION
    ADD CONSTRAINT ACT_FK_EXE_PROCINST
    FOREIGN KEY (PROC_INST_ID_)
    REFERENCES ACT_RU_EXECUTION (ID_) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ACT_RU_EXECUTION
    ADD CONSTRAINT ACT_FK_EXE_PARENT
    FOREIGN KEY (PARENT_ID_)
    REFERENCES ACT_RU_EXECUTION (ID_);
    
ALTER TABLE ACT_RU_EXECUTION
    ADD CONSTRAINT ACT_FK_EXE_SUPER
    FOREIGN KEY (SUPER_EXEC_)
    REFERENCES ACT_RU_EXECUTION (ID_);
    
ALTER TABLE ACT_RU_IDENTITYLINK
    ADD CONSTRAINT ACT_FK_TSKASS_TASK
    FOREIGN KEY (TASK_ID_)
    REFERENCES ACT_RU_TASK (ID_);
    
ALTER TABLE ACT_RU_IDENTITYLINK
    ADD CONSTRAINT ACT_FK_ATHRZ_PROCEDEF
    FOREIGN KEY (PROC_DEF_ID_)
    REFERENCES ACT_RE_PROCDEF(ID_);
    
ALTER TABLE ACT_RU_TASK
    ADD CONSTRAINT ACT_FK_TASK_EXE
    FOREIGN KEY (EXECUTION_ID_)
    REFERENCES ACT_RU_EXECUTION (ID_);
    
ALTER TABLE ACT_RU_TASK
    ADD CONSTRAINT ACT_FK_TASK_PROCINST
    FOREIGN KEY (PROC_INST_ID_)
    REFERENCES ACT_RU_EXECUTION (ID_);
    
ALTER TABLE ACT_RU_TASK
  ADD CONSTRAINT ACT_FK_TASK_PROCDEF
  FOREIGN KEY (PROC_DEF_ID_)
  REFERENCES ACT_RE_PROCDEF (ID_);
  
ALTER TABLE ACT_RU_VARIABLE
    ADD CONSTRAINT ACT_FK_VAR_EXE
    FOREIGN KEY (EXECUTION_ID_)
    REFERENCES ACT_RU_EXECUTION (ID_);

ALTER TABLE ACT_RU_VARIABLE
    ADD CONSTRAINT ACT_FK_VAR_PROCINST
    FOREIGN KEY (PROC_INST_ID_)
    REFERENCES ACT_RU_EXECUTION(ID_);

ALTER TABLE ACT_RU_VARIABLE
    ADD CONSTRAINT ACT_FK_VAR_BYTEARRAY
    FOREIGN KEY (BYTEARRAY_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_JOB
    ADD CONSTRAINT ACT_FK_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_EVENT_SUBSCR
    ADD CONSTRAINT ACT_FK_EVENT_EXEC
    FOREIGN KEY (EXECUTION_ID_)
    REFERENCES ACT_RU_EXECUTION(ID_);