DROP index ACT_IDX_EXEC_BUSKEY;
DROP index ACT_IDX_TASK_CREATE;
DROP index ACT_IDX_IDENT_LNK_USER;
DROP index ACT_IDX_IDENT_LNK_GROUP;
DROP index ACT_IDX_VARIABLE_TASK_ID;

ALTER TABLE ACT_GE_BYTEARRAY
    DROP CONSTRAINT ACT_FK_BYTEARR_DEPL;

ALTER TABLE ACT_RU_EXECUTION
    DROP CONSTRAINT ACT_FK_EXE_PROCINST;

ALTER TABLE ACT_RU_EXECUTION
    DROP CONSTRAINT ACT_FK_EXE_PARENT;

ALTER TABLE ACT_RU_EXECUTION
    DROP CONSTRAINT ACT_FK_EXE_SUPER;
    
ALTER TABLE ACT_RU_EXECUTION
    DROP CONSTRAINT ACT_UNIQ_RU_BUS_KEY;
    
ALTER TABLE ACT_RU_IDENTITYLINK
    DROP CONSTRAINT ACT_FK_TSKASS_TASK;

ALTER TABLE ACT_RU_IDENTITYLINK
    DROP CONSTRAINT ACT_FK_ATHRZ_PROCEDEF;

ALTER TABLE ACT_RU_TASK
	DROP CONSTRAINT ACT_FK_TASK_EXE;

ALTER TABLE ACT_RU_TASK
	DROP CONSTRAINT ACT_FK_TASK_PROCINST;
	
ALTER TABLE ACT_RU_TASK
	DROP CONSTRAINT ACT_FK_TASK_PROCDEF;
	
ALTER TABLE ACT_RU_VARIABLE
    DROP CONSTRAINT ACT_FK_VAR_EXE;
    
ALTER TABLE ACT_RU_VARIABLE
    DROP CONSTRAINT ACT_FK_VAR_PROCINST;
    
ALTER TABLE ACT_RU_VARIABLE
    DROP CONSTRAINT ACT_FK_VAR_BYTEARRAY;

ALTER TABLE ACT_RU_JOB
    DROP CONSTRAINT ACT_FK_JOB_EXCEPTION;
    
ALTER TABLE ACT_RU_EVENT_SUBSCR
    DROP CONSTRAINT ACT_FK_EVENT_EXEC;

ALTER TABLE ACT_RE_PROCDEF
    DROP CONSTRAINT ACT_UNIQ_PROCDEF;

DROP index ACT_IDX_EVENT_SUBSCR_CONFIG_;
DROP index ACT_IDX_ATHRZ_PROCEDEF;
    
DROP TABLE ACT_GE_PROPERTY if EXISTS;
DROP TABLE ACT_GE_BYTEARRAY if EXISTS;
DROP TABLE ACT_RE_DEPLOYMENT if EXISTS;
DROP TABLE ACT_RU_EXECUTION if EXISTS;
DROP TABLE ACT_RU_JOB if EXISTS;
DROP TABLE ACT_RE_PROCDEF if EXISTS;
DROP TABLE ACT_RU_TASK if EXISTS;
DROP TABLE ACT_RU_IDENTITYLINK if EXISTS;
DROP TABLE ACT_RU_VARIABLE if EXISTS;
DROP TABLE ACT_RU_EVENT_SUBSCR if EXISTS;
