ALTER TABLE ACT_ID_MEMBERSHIP
    DROP CONSTRAINT ACT_FK_MEMB_GROUP;
    
ALTER TABLE ACT_ID_MEMBERSHIP
    DROP CONSTRAINT ACT_FK_MEMB_USER;
    
DROP TABLE ACT_ID_INFO if EXISTS;
DROP TABLE ACT_ID_GROUP if EXISTS;
DROP TABLE ACT_ID_MEMBERSHIP if EXISTS;
DROP TABLE ACT_ID_USER if EXISTS;
