DROP index ACT_IDX_HI_PRO_INST_END ON ACT_HI_PROCINST;
DROP index ACT_IDX_HI_PRO_I_BUSKEY ON ACT_HI_PROCINST;
DROP index ACT_IDX_HI_ACT_INST_START ON ACT_HI_ACTINST;
DROP index ACT_IDX_HI_ACT_INST_END ON ACT_HI_ACTINST;
DROP index ACT_IDX_HI_DETAIL_PROC_INST ON ACT_HI_DETAIL;
DROP index ACT_IDX_HI_DETAIL_ACT_INST ON ACT_HI_DETAIL;
DROP index ACT_IDX_HI_DETAIL_TIME ON ACT_HI_DETAIL;
DROP index ACT_IDX_HI_DETAIL_NAME ON ACT_HI_DETAIL;
DROP index ACT_IDX_HI_DETAIL_TASK_ID ON ACT_HI_DETAIL;

DROP TABLE if EXISTS ACT_HI_PROCINST;
DROP TABLE if EXISTS ACT_HI_ACTINST;
DROP TABLE if EXISTS ACT_HI_TASKINST;
DROP TABLE if EXISTS ACT_HI_DETAIL;
DROP TABLE if EXISTS ACT_HI_COMMENT;
DROP TABLE if EXISTS ACT_HI_ATTACHMENT;
 