ALTER TABLE ACT_ID_MEMBERSHIP
    DROP FOREIGN KEY ACT_FK_MEMB_GROUP;
    
ALTER TABLE ACT_ID_MEMBERSHIP
    DROP FOREIGN KEY ACT_FK_MEMB_USER;

DROP TABLE if EXISTS ACT_ID_INFO;
DROP TABLE if EXISTS ACT_ID_MEMBERSHIP;
DROP TABLE if EXISTS ACT_ID_GROUP;
DROP TABLE if EXISTS ACT_ID_USER;
